/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkTimeSettingRouteImport } from './routes/walk-time-setting'
import { Route as StartWalkRouteImport } from './routes/start-walk'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MapSetupRouteImport } from './routes/map-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationSettingRouteImport } from './routes/location-setting'
import { Route as AddNewPetRouteImport } from './routes/add-new-pet'
import { Route as IndexRouteImport } from './routes/index'

const WalkTimeSettingRoute = WalkTimeSettingRouteImport.update({
  id: '/walk-time-setting',
  path: '/walk-time-setting',
  getParentRoute: () => rootRouteImport,
} as any)
const StartWalkRoute = StartWalkRouteImport.update({
  id: '/start-walk',
  path: '/start-walk',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MapSetupRoute = MapSetupRouteImport.update({
  id: '/map-setup',
  path: '/map-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSettingRoute = LocationSettingRouteImport.update({
  id: '/location-setting',
  path: '/location-setting',
  getParentRoute: () => rootRouteImport,
} as any)
const AddNewPetRoute = AddNewPetRouteImport.update({
  id: '/add-new-pet',
  path: '/add-new-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-new-pet': typeof AddNewPetRoute
  '/location-setting': typeof LocationSettingRoute
  '/login': typeof LoginRoute
  '/map-setup': typeof MapSetupRoute
  '/mypage': typeof MypageRoute
  '/start-walk': typeof StartWalkRoute
  '/walk-time-setting': typeof WalkTimeSettingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-new-pet': typeof AddNewPetRoute
  '/location-setting': typeof LocationSettingRoute
  '/login': typeof LoginRoute
  '/map-setup': typeof MapSetupRoute
  '/mypage': typeof MypageRoute
  '/start-walk': typeof StartWalkRoute
  '/walk-time-setting': typeof WalkTimeSettingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-new-pet': typeof AddNewPetRoute
  '/location-setting': typeof LocationSettingRoute
  '/login': typeof LoginRoute
  '/map-setup': typeof MapSetupRoute
  '/mypage': typeof MypageRoute
  '/start-walk': typeof StartWalkRoute
  '/walk-time-setting': typeof WalkTimeSettingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-new-pet'
    | '/location-setting'
    | '/login'
    | '/map-setup'
    | '/mypage'
    | '/start-walk'
    | '/walk-time-setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-new-pet'
    | '/location-setting'
    | '/login'
    | '/map-setup'
    | '/mypage'
    | '/start-walk'
    | '/walk-time-setting'
  id:
    | '__root__'
    | '/'
    | '/add-new-pet'
    | '/location-setting'
    | '/login'
    | '/map-setup'
    | '/mypage'
    | '/start-walk'
    | '/walk-time-setting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddNewPetRoute: typeof AddNewPetRoute
  LocationSettingRoute: typeof LocationSettingRoute
  LoginRoute: typeof LoginRoute
  MapSetupRoute: typeof MapSetupRoute
  MypageRoute: typeof MypageRoute
  StartWalkRoute: typeof StartWalkRoute
  WalkTimeSettingRoute: typeof WalkTimeSettingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walk-time-setting': {
      id: '/walk-time-setting'
      path: '/walk-time-setting'
      fullPath: '/walk-time-setting'
      preLoaderRoute: typeof WalkTimeSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-walk': {
      id: '/start-walk'
      path: '/start-walk'
      fullPath: '/start-walk'
      preLoaderRoute: typeof StartWalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-setup': {
      id: '/map-setup'
      path: '/map-setup'
      fullPath: '/map-setup'
      preLoaderRoute: typeof MapSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-setting': {
      id: '/location-setting'
      path: '/location-setting'
      fullPath: '/location-setting'
      preLoaderRoute: typeof LocationSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-new-pet': {
      id: '/add-new-pet'
      path: '/add-new-pet'
      fullPath: '/add-new-pet'
      preLoaderRoute: typeof AddNewPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddNewPetRoute: AddNewPetRoute,
  LocationSettingRoute: LocationSettingRoute,
  LoginRoute: LoginRoute,
  MapSetupRoute: MapSetupRoute,
  MypageRoute: MypageRoute,
  StartWalkRoute: StartWalkRoute,
  WalkTimeSettingRoute: WalkTimeSettingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
